services:
  fastapi:
    container_name: fastapi
    restart: unless-stopped
    build:
      context: ./src/fastapi
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - ingress

# for testing with the GrantBirki/ingress project
networks:
  ingress:
    name: ingress
    external: true
